SRC = srcs/ft_putstr.c
NAME = "ft_display_file"
HEADER = includes/ft.h
MAIN = main.c

all :
	gcc -c -Wall -Wextra -Werror $(SRC) $(MAIN) 
	gcc -o $(NAME) *.o
clean :
	/bin/rm -f *.o
fclean : clean
	/bin/rm -f $(NAME)


